### ISSUE TITLE
stem + asyncio

### ISSUE THREAD

**Issue by kaa-szhk** [torproject/stem#114]
Hello!
Any small examples how to use asyncio with stem ?
Or only the  https://blog.atagar.com/july2020/ ?
Thanks!

**Comment by atagar** [comment]
Hi  kaa-szhk, sorry for the delay. I've been out of commission sick.

Stem's asyncio functionality is in a rough, alpha state. In fact, if I returned to Stem development I'd remove much of it since the hybrid sync/async approach I came up with [doesn't work very well](https://github.com/torproject/stem/issues/77). I'd advise against using the master branch for production code but that said, if you'd care to use feel free.

Sorry I don't have better news for you. I left Tor about a year ago and nobody's taken the project up so unfortunately Stem's been on ice since. :(
